apiVersion: apps/v1
kind: Deployment
metadata:
  name: clode-studio
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: clode-studio
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "warn"