apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: clode-studio
  annotations:
    config.kubernetes.io/local-config: "true"

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: clode-studio
  app.kubernetes.io/managed-by: kustomize

# Resources to include
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Images to use (can be overridden)
images:
  - name: ghcr.io/haidar-ali/clode-studio
    newTag: latest

# ConfigMap generator for additional configuration
configMapGenerator:
  - name: clode-studio-env
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info

# Namespace for all resources
namespace: clode-studio

# Patches for different environments
patchesStrategicMerge:
  - patches/production.yaml

# Resource ordering
transformers:
  - patches/add-security-context.yaml